### ISSUE TITLE
How to initialize ctor from the editor

### ISSUE THREAD

**Issue by theGhostJW** [KreativJos/csharpextensions#10]
How do you invoke ```initialize ctor``` from the editor? I can't see how it is done fromm the gif.

**Comment by KreativJos** [comment]
To be honest, I have no idea. I have tested it quite some time ago, but I cannot seem to get the commands anywhere.
It seems like the commands api has changed, because I cannot find the commands in the 'Feature Contributions':
![image](https://user-images.githubusercontent.com/20839414/80955051-d7cd7f80-8dfe-11ea-9f73-03d288490976.png)

**Comment by PoLaKoSz** [comment]
The `Initialize ctor from properties...` still working in `v1.3.6` because the command is registered: https://github.com/KreativJos/csharpextensions/blob/dcb4e82fc1eb4c26db73724031d44fb5c7c98bc5/src/codeActionProvider.ts#L13

You need at least one property and if I type `Ctrl` + `.` (I didn't change any keybord shortcuts [VS Code v1.51.1]) inside a C# class (some empty place will do) the popup will open up with the option.
