### ISSUE TITLE
Cannot read properties of undefined (reading 'properties')

### ISSUE THREAD

**Issue by Alluseri** [KreativJos/csharpextensions#102]
**Describe the bug**
Running the "csharpextensions.ctorFromProperties" command yields the error "Cannot read properties of undefined (reading 'properties')". See the subject source code in screenshots.

**Context**
- 1.7.0
- VSCodium 1.68.1
- Windows 8.1
- The context menu entry isn't shown at all, which means... it doesn't see my class as a proper C# class? Maybe?

**Expected behavior**
A constructor would be generated for my class properties.

**Screenshots**
<img src="https://cdn.discordapp.com/attachments/853155168170147910/993998854225674381/unknown.png">
<img src="https://cdn.discordapp.com/attachments/853155168170147910/993999485057368114/unknown.png">

**Comment by KreativJos** [comment]
There are no properties in the class you created, which is why the command is not shown. Those items are public fields (which is a bad practice).
You could use the 'Generate constructor' function from omnisharp, which works by selecting all text with fields / properties and then generates a constructor with those fields / properties.
