### ISSUE TITLE
Use current directory when creating new classes/interfaces

### ISSUE THREAD

**Issue by JotaRata** [KreativJos/csharpextensions#117]
When invoking the "Class" or "Interface" o "Struct"... etc commands in the Command palette it should create the new file inside the directory of the file you're working on (or at least be configurable) instead of being created in the root directory of the project.

**Comment by bard83** [comment]
> create the new file inside the directory of the file you're working on

The main question would be: which directory should be considered the working directory? The one actually related to the active file opened in the editor? or the directory that is selected in the explorer's files tree? when none of them are evaluated - again the question - which should be considered working directory? workspace directory?

> at least be configurable

well, it will mean that the path should be part again of the input dialog. Solution which I don't tend for, because it will require some checks during the file creation.

I want to fix it for sure, what I can offer is the following: 
it will be considered working directory the one related to the active file opened in the editor, in case there are no files opened then it will be used the workspace folder.

**Comment by bard83** [comment]
the [1.8.0](https://marketplace.visualstudio.com/items?itemName=bard83.csharpextension) is out. This feature is part of it.
