### ISSUE TITLE
Empty templates folder

### ISSUE THREAD

**Issue by DonPangPang** [KreativJos/csharpextensions#66]
The templates folder is empty!
![image](https://user-images.githubusercontent.com/49866401/157161089-5fb53ae3-5631-45fc-8342-cd7b30f72c72.png)

**Comment by KreativJos** [comment]
That is kind of weird. I will try to reproduce on a clean install.

**Comment by KreativJos** [comment]
![image](https://user-images.githubusercontent.com/20839414/157462514-ee054885-8e8a-4c97-a003-a96909a0116f.png)
Works fine for me on a clean install.
I did have some issues trying to install, vscode took an older version, because that had been installed previously. To resolve that, I had to uninstall the extension, restart my pc (relogin could have done the job I think) & then install it again.

To resolve this for you personally, you can just download all templates from the folder here on github: https://github.com/KreativJos/csharpextensions/tree/master/templates

**Comment by DonPangPang** [comment]
> ![image](https://user-images.githubusercontent.com/20839414/157462514-ee054885-8e8a-4c97-a003-a96909a0116f.png) Works fine for me on a clean install. I did have some issues trying to install, vscode took an older version, because that had been installed previously. To resolve that, I had to uninstall the extension, restart my pc (relogin could have done the job I think) & then install it again.
> 
> To resolve this for you personally, you can just download all templates from the folder here on github: https://github.com/KreativJos/csharpextensions/tree/master/templates

Yes, I have obtained the template through this method. Thank you for your support.
